// Code generated by goctl. DO NOT EDIT!
// Source: photoExhibition.proto

package server

import (
	"context"

	"blog/service/photoExhibition/rpc/internal/logic"
	"blog/service/photoExhibition/rpc/internal/svc"
	"blog/service/photoExhibition/rpc/types/photoExhibition"
)

type PhotoExhibitionServer struct {
	svcCtx *svc.ServiceContext
	photoExhibition.UnimplementedPhotoExhibitionServer
}

func NewPhotoExhibitionServer(svcCtx *svc.ServiceContext) *PhotoExhibitionServer {
	return &PhotoExhibitionServer{
		svcCtx: svcCtx,
	}
}

func (s *PhotoExhibitionServer) CreatePhotoExhibition(ctx context.Context, in *photoExhibition.CreatePhotoExhibitionReq) (*photoExhibition.CreatePhotoExhibitionRes, error) {
	l := logic.NewCreatePhotoExhibitionLogic(ctx, s.svcCtx)
	return l.CreatePhotoExhibition(in)
}

func (s *PhotoExhibitionServer) EditPhotoExhibition(ctx context.Context, in *photoExhibition.EditPhotoExhibitionReq) (*photoExhibition.EditPhotoExhibitionRes, error) {
	l := logic.NewEditPhotoExhibitionLogic(ctx, s.svcCtx)
	return l.EditPhotoExhibition(in)
}

func (s *PhotoExhibitionServer) DelPhotoExhibition(ctx context.Context, in *photoExhibition.DelPhotoExhibitionReq) (*photoExhibition.DelPhotoExhibitionRes, error) {
	l := logic.NewDelPhotoExhibitionLogic(ctx, s.svcCtx)
	return l.DelPhotoExhibition(in)
}

func (s *PhotoExhibitionServer) EditStatus(ctx context.Context, in *photoExhibition.EditStatusReq) (*photoExhibition.EditStatusRes, error) {
	l := logic.NewEditStatusLogic(ctx, s.svcCtx)
	return l.EditStatus(in)
}

func (s *PhotoExhibitionServer) PhotoExhibitionInfo(ctx context.Context, in *photoExhibition.PhotoExhibitionInfoReq) (*photoExhibition.PhotoExhibitionInfoRes, error) {
	l := logic.NewPhotoExhibitionInfoLogic(ctx, s.svcCtx)
	return l.PhotoExhibitionInfo(in)
}
