// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Username string `form:"username"`
	Password string `form:"password"`
}

type LoginRes struct {
	Id        int64   `json:"id"`
	Username  string  `json:"username"`
	Password  string  `json:"password,omitempty"`
	Gender    int     `json:"gender,omitempty"`
	Age       int     `json:"age,omitempty"`
	Birthday  *int64  `json:"birthday,omitempty"`
	Address   string  `json:"address,omitempty"`
	Tel       *int    `json:"tel,omitempty"`
	Email     *string `json:"email,omitempty"`
	AvatarUrl string  `json:"avatar_url,omitempty"`
	Token     string  `json:"token"`
}

type RegisterReq struct {
	Username string `form:"username"`
	Password string `form:"password"`
	Tel      string `form:"tel"`
}

type RegisterRes struct {
	Id int `json:"id"`
}
