// Code generated by goctl. DO NOT EDIT.
package types

type CreatePhotoExhibitionReq struct {
	Title    string `form:"title"`
	SubTitle string `form:"sub_title"`
	Des      string `form:"des"`
	Cover    string `form:"cover"`
}

type CreatePhotoExhibitionRes struct {
	Id int `json:"id"`
}

type PhotoExhibitionInfoReq struct {
	Id string `form:"id"`
}

type PhotoExhibitionInfoRes struct {
	Id        uint     `json:"id"`
	Title     string   `json:"title"`
	SubTitle  string   `json:"sub_title"`
	Des       string   `json:"des"`
	Cover     string   `json:"cover"`
	UserId    uint     `json:"user_id"`
	Status    int      `json:"status"`     // 1待审核 2审核通过 3未通过审核
	RejectRes string   `json:"reject_res"` // 驳回原因
	UserInfo  UserInfo `json:"user_info"`
}

type UserInfo struct {
	Username  string `json:"username"`
	Gender    int    `json:"gender"`
	AvatarUrl string `json:"avatar_url"`
}
